version: '2.2'

services:
  frontend:
    image: portifolio
    build: .
    ports:
      - "5000:5000"
    restart: on-failure
    container_name: portifolio
    volumes:
      - .:/app
      - /app/node_modules