version: '2.2'

services:
  frontend:
    image: portfolio
    build: .
    ports:
      - "5000:5000"
    restart: on-failure
    container_name: portfolio
    volumes:
      - .:/app
      - /app/node_modules